### Send POST request with json body
POST http://localhost:8080/sync-batch
Content-Type: application/json

{
  "id": "leaven"
}

### Send POST request with json body
POST http://localhost:8080/async-batch
Content-Type: application/json

{
  "id": "leaven"
}
